# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_app', '0004_auto_20170309_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='recipe',
            field=models.ManyToManyField(related_name='categories', to='cooking_app.Recipe'),
        ),
    ]
