# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_app', '0005_auto_20170309_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cooking_app.Recipe'),
        ),
    ]
