# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_app', '0006_auto_20170309_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_recipes', to='loginRegistration_app.User'),
        ),
    ]
